export const SPACE_BAR_UP ='SPACE_BAR_UP'
export const ARROW_UP_UP = 'ARROW_UP_UP'
export const ARROW_RIGHT_UP = 'ARROW_RIGHT_UP'
export const ARROW_DOWN_UP = 'ARROW_DOWN_UP'
export const ARROW_LEFT_UP = 'ARROW_LEFT_UP'
export const SPACE_BAR_DOWN ='SPACE_BAR_DOWN'
export const ARROW_UP_DOWN = 'ARROW_UP_DOWN'
export const ARROW_RIGHT_DOWN = 'ARROW_RIGHT_UP'
export const ARROW_DOWN_DOWN = 'ARROW_DOWN_DOWN'
export const ARROW_LEFT_DOWN = 'ARROW_LEFT_DOWN'

export const COLLISION = 'COLLISION'
export const GOAL = 'GOAL'
export const GAME_OVER = 'GAME_OVER'
